version: '3'

services:
  ruby:
    container_name: ruby
    hostname: ruby
  build:
    context: ./docker/rack
    dockerfile: Dockerfile
  depends_on:
    - ad
    - nt
  entrypoint:
    - tail -f /dev/null
  volumes:
    - .:/opt/app

  ad:
    container_name: ad
    hostname: ad
    image: tsutomu/docker-samba-ad
    privileged: true

  nt:
    container_name: nt
    hostname: nt
    image: tsutomu/docker-samba-nt
    privileged: true

