version: '3'

services:
  ruby:
    container_name: ad-ruby
    image: tsutomu/adap:docker_bundle_v2.1.2
    hostname: ruby
    depends_on:
      - nt
    entrypoint:
      - /opt/entrypoint.sh
    volumes:
      - .:/opt/app
    privileged: true

  nt:
    container_name: nt
    hostname: nt
    image: tsutomu/docker-samba-nt
    privileged: true

