version: '3'

services:
  ruby:
    container_name: ad-ruby
    hostname: ruby
    build:
      context: ./dockerfile
      dockerfile: Dockerfile
    depends_on:
      - ad
      - nt
    entrypoint:
      - tail
      - -f
      - /dev/null
    volumes:
      - .:/opt/app

  nt:
    container_name: nt
    hostname: nt
    image: tsutomu/docker-samba-nt
    privileged: true

