# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  workflow_dispatch:    # Allows you to run this workflow manually from the Actions tab or GitHub CLI(gh workflow run)
    inputs:
      otp:
        description: "One-time password for RubyGems.org"
        required: true
  push:
    tags: ["v*"]
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest]
        os: [ubuntu-24.04]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: ['3.3']
    runs-on: ${{ matrix.os }}
    env:
      GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      GEM_HOST_OTP_CODE: ${{ github.event.inputs.rubygems-otp-code }}

    steps:
    - name: Print variables that will be used
      run: |
        # You can list GitHub Actionses variables with a command below.
        # $ grep -oP '\$\{\{.*?\}\}' .github/workflows/docker-image.yml | sort | uniq
        echo env.dest_repository_name=${{ env.dest_repository_name }}
        echo env.dest_repository_owner_name=${{ env.dest_repository_owner_name }}
        echo github.event.repository.name=${{ github.event.repository.name }}
        echo github.event.repository.owner.name=${{ github.event.repository.owner.name }}

    - name: Check out ${{ github.event.repository.owner.name }}/${{ github.event.repository.name }}
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      #uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Run tests
      run: |
        cd ${GITHUB_WORKSPACE}/${{ github.event.repository.name }}
        bundle install --retry 3
        bundle exec rake

    - name: Push to rubygems.org
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo "Pushing to rubygems.org. You need update the version in lib/adap/version.rb before pushing it."
        echo "Detected version is \"$(grep VERSION lib/adap/version.rb)\""
        cd ${GITHUB_WORKSPACE}/${{ github.event.repository.name }}
        bundle exec rake release

