# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    container:
      image: ruby:3.3
    strategy:
      matrix:
        ruby-version: ['3.2']

    steps:
    - name: Print variables that will be used
      run: |
        # You can list GitHub Actionses variables with a command below.
        # $ grep -oP '\$\{\{.*?\}\}' .github/workflows/docker-image.yml | sort | uniq
        echo env.dest_repository_name=${{ env.dest_repository_name }}
        echo env.dest_repository_owner_name=${{ env.dest_repository_owner_name }}
        echo github.event.repository.name=${{ github.event.repository.name }}
        echo github.event.repository.owner.name=${{ github.event.repository.owner.name }}

    - name: Check out ${{ github.event.repository.owner.name }}/${{ github.event.repository.name }}
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Run tests
      run: |
        cd ${GITHUB_WORKSPACE}/${{ github.event.repository.name }}
        bundle install --retry 3
        bundle exec rake
